id: '1702660654016'
alias: Dog Medication Reminder
description: ''
trigger:
- platform: time
  at: 08:00:00
condition:
- condition: template
  value_template: '{{ now().day == 15 }}'
action:
- service: notify.mobile_app_johns_phone
  data:
    message: Reminder to give HeartGuard and NexGuard to Parsley
    title: Mediation Reminder
- service: notify.mobile_app_christine_timons_iphone
  data:
    message: Reminder to give HeartGuard and NexGuard to Parsley
    title: Mediation Reminder
mode: single



