# Time of day sensor
- platform: workday
  country: US
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun, holiday]
  add_holidays:
    - "2020-10-09"
    - "2020-10-15"
    - "2020-10-16"

- platform: tod
  name: Early Morning
  after: sunrise
  after_offset: "-00:45"
  before: "08:00"

- platform: tod
  name: Morning
  after: "08:00"
  before: "12:00"

- platform: tod
  name: Afternoon
  after: "12:00"
  before: sunset
  before_offset: "-00:30"

- platform: tod
  name: Evening
  after: sunset
  after_offset: "-00:30"
  before: "20:30"

- platform: tod
  name: Night
  after: "20:30"
  before: "23:59"

- platform: tod
  name: Work Hours
  after: "08:00"
  before: "17:00"

## Presence Sensor
- platform: template
  sensors:
    anyone_home:
      device_class: presence
      friendly_name: "House Occupied"
      value_template: "{{ states.person | selectattr('state','eq','home') | list | count > 0 }}"
    downstairs_bathroom_humidity_status:
      friendly_name: Downstairs Bathroom Humidity Status
      value_template: >-
        {% set humid = states('sensor.zooz_downstairs_bathroom_humidity')|int(default=0) %}
        {% set avg = states('sensor.downstairs_bathroom_humidity_average_linear_24h')|int(default=0) %}
        {% set thresh = 5 %}
        {{ (humid - avg) > thresh }}
      unique_id: "downstairs_bathrrom_humidity_status"


# Ping gateway
- platform: ping
  host: 192.168.0.1
  name: Gateway Ping
  count: 2
  scan_interval: 30

# Ping gateway
- platform: ping
  host: xfinity.com
  name: Xfinity
  count: 2
  scan_interval: 30
