#========================
# Valve Binary Sensor
#========================
#- platform: mqtt
#  name: "Pool Valve State"
#  state_topic: "poolduino-valve/valveState"
#  payload_on: "1"
#  payload_off: "0"
#  device_class: "running"
#  unique_id: "poolduino-valve__state"

#========================
# Pool Binary Sensor
#========================
- platform: mqtt
  name: "Pool Water Level"
  state_topic: "homie/PoolDuino-pool/level/level"
  payload_on: "Low"
  payload_off: "High"
  unique_id: "pool_water__waterlevel"

#========================
# Pool Valve Binary Sensor
#========================
#- platform: mqtt
#  name: "Pool Valve Water Level"
#  state_topic: "poolduino-valve/waterLevel"
#  unique_id: "poolduino-valve__waterlevel"
#  payload_off: "High"
#  payload_on: "Low"

#========================
# RF Gateway Binary Sensor
#========================
#- platform: mqtt
#  name: "Man Door"
#  state_topic: "rfgateway1-out/6/1/1/0/16"
#  payload_on: "1"
#  payload_off: "0"
#  device_class: "door"
#  unique_id: "man_door__state"
#- platform: mqtt
#  name: "Basement Slider Door"
#  state_topic: "rfgateway1-out/7/1/1/0/16"
#  payload_on: "1"
#  payload_off: "0"
#  device_class: "door"
#  unique_id: "basement_slider__state"

# Time of day sensor
- platform: workday
  country: US
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun, holiday]
  add_holidays:
    - "2020-10-09"
    - "2020-10-15"
    - "2020-10-16"

- platform: tod
  name: Early Morning
  after: sunrise
  after_offset: "-00:45"
  before: "08:00"

- platform: tod
  name: Morning
  after: "08:00"
  before: "12:00"

- platform: tod
  name: Afternoon
  after: "12:00"
  before: sunset
  before_offset: "-02:30"

- platform: tod
  name: Evening
  after: sunset
  after_offset: "-02:30"
  before: "20:30"

- platform: tod
  name: Night
  after: "20:30"
  before: "23:59"
