#========================
# Valve Switch
#========================
- platform: mqtt
  name: "Pool Valve Autofill"
  state_topic: "poolduino-valve/autofill"
  command_topic: "poolduino-valve/autofill/set"
  payload_on: "1"
  payload_off: "0"
  unique_id: "poolduino-valve__autofill"
