sensor:
  unique_id: washing_machine_sensor
  name: Washing Machine is Running
  state: >-
    {% if states('sensor.washing_machine_power')|float > 1 %}
      true
    {% else %}
      false
    {% endif %}

sensor:
  unique_id: dryer_sensor
  name: Dryer is Running
  state: >-
    {% if states('sensor.dryer_16_1min')|float > 10 %}
      true
    {% else %}
      false
    {% endif %}
