alias: Master Bathroom Door opens
description: ''
trigger:
  - platform: state
    entity_id:
      - binary_sensor.lumi_master_bathroom_contact_1
    from: 'off'
    to: 'on'
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.evening
        state: 'on'
      - condition: state
        entity_id: binary_sensor.night
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.kitchen_lux
        below: 300
action:
  - service: light.turn_on
    data:
      brightness_pct: 15
      rgb_color: [255, 191, 0]
    target:
      entity_id: light.under_cabinet_light
mode: single
