binary_sensor:
#========================
# Pool Binary Sensor
#========================
- name: "Pool Water Level"
  state_topic: "homie/PoolDuino-pool/level/level"
  payload_on: "Low"
  payload_off: "High"
  unique_id: "pool_water__waterlevel"