sensor:

  - name: "Pool Temperature"
    device_class: "temperature"
    state_topic: "homie/PoolDuino-pool/temperature/degrees"
    unique_id: "poolduino_pool_temperature"
    unit_of_measurement: "°F"
#
#platform: mqtt
#name: "Garage Shelly"
#state_topic: "homie/PoolDuino-pool/temperature/degrees"
#unique_id: "poolduino_pool_temperature"
#unit_of_measurement: "°F"
