id: 'hristineoutofbed'
alias: CHristine's underbed light on
description: 'Christine gets out of bed '
trigger:
- platform: state
  entity_id:
  - binary_sensor.christine_in_bed
  from: 'on'
  to: 'off'
condition:
- condition: time
  after: '20:00:00'
  before: 06:30:00
action:
- service: light.turn_on
  data:
    brightness_pct: 25
    rgb_color: 
    - 255
    - 191
    - 0
  target:
    entity_id:
    - light.left_underbed
    - light.under_cabinet_light
mode: single