id: 'christineinbed'
alias: CHristine's underbed light off
description: 'Christine gets in to bed '
trigger:
- platform: state
  entity_id:
  - binary_sensor.christine_in_bed
  from: 'off'
  to: 'on'
condition:
- condition: time
  after: '17:00:00'
  before: 08:00:00
action:
- service: light.turn_off
  target:
    entity_id: 
    - light.left_underbed
    - light.under_cabinet_light
mode: single