alias: Notify Dryer Cycle Completed
trigger:
  - entity_id: sensor.dryer_is_running
    platform: state
    to: "false"
    for:
      minutes: 1
condition:
  condition: state
  entity_id:
    - person.christine
  state: "home"
action:
  service: notify.mobile_app_christine_timons_iphone
  data:
    message: "The dryer has finished its cycle"
    title: Dryer Done
