alias: Notify Dryer Cycle Completed
trigger:
  - entity_id: sensor.dryer_is_running
    platform: state
    to: "false"
    for:
      minutes: 1
action:
  service: notify.mobile_app_christine_timons_iphone_13
  data:
    message: "The dryer has finished its cycle"
    title: Dryer Done
