alias: Notify Dryer Cycle Completed
triggers:
  - entity_id: sensor.dryer_is_running
    trigger: state
    from: "true"
    to: "false"
    for:
      minutes: 1
condition:
  condition: state
  entity_id:
    - person.christine
  state: "home"
actions:
  - action: notify.mobile_app_christine_timons_iphone
    data:
      message: "The dryer has finished its cycle"
      title: Dryer Done
