id: 'johnoutbed'
alias: John's underbed light on
description: 'John gets out of bed '
trigger:
- platform: state
  entity_id:
  - binary_sensor.john_in_bed
  from: 'on'
  to: 'off'
condition:
- condition: time
  after: '17:00:00'
  before: 08:00:00
action:
- service: light.turn_on
  data:
    brightness_pct: 100
  target:
    entity_id: light.right_underbed
mode: single