alias: Master bedroom door open
trigger:
  - entity_id: binary_sensor.lumi_master_bedroom_contact_1
    platform: state
    to: "on"
action:
  service: notify.mobile_app_christine_timons_iphone
  data:
    message: "The Master Bedroom Door has opened"
    title: "Master Bedroom Door"
