alias: Master bedroom door open
triggers:
  - entity_id: binary_sensor.lumi_master_bedroom_contact_1
    trigger: state
    from: "off"
    to: "on"
actions:
  - action: notify.mobile_app_christine_timons_iphone
    data:
      message: "The Master Bedroom Door has opened"
      title: "Master Bedroom Door"
