alias: Notify Wash Cycle Completed
trigger:
  - entity_id: sensor.washing_machine_is_running
    platform: state
    to: "false"
    for:
      minutes: 1
condition:
  condition: state
  entity_id:
    - person.christine
  state: "home"
action:
  service: notify.mobile_app_christine_timons_iphone_13
  data:
    message: "The washing machine has finished its cycle"
    title: Washing Machine Done
