trigger:
  platform: state
  entity_id: binary_sensor.lumi_downstairs_bathroom_contact
  to: 'off'
  for: 00:05:00
condition:
  condition: state
  entity_id:
    - input_boolean.downstairs_washroom_occupied
  state: "off"
action:
- service: light.turn_off
  entity_id: light.downstairs_bathroom_vanity_lights
alias: motion ended downstairs washroom lights off