trigger:  
  platform: state
  entity_id: binary_sensor.garage_motion_new
  to: 'off'
  for: 00:03:00
action:
  service: switch.turn_off
  entity_id: switch.garage_lights
alias: motion garage light off
