trigger:  
  platform: state
  entity_id: binary_sensor.tuya_garage_motion_sensor_motion
  to: 'off'
  for: 00:03:00
action:
  service: light.turn_off
  entity_id: light.garage_lights_3
alias: motion garage light off
