trigger:
  platform: state
  entity_id: binary_sensor.hallway_motion_sensor
  to: 'off'
  for: 00:02:00
action:
  service: switch.turn_off
  entity_id: switch.hallway_light
alias: motion hallway light off
