trigger:
- platform: state
  entity_id: binary_sensor.kitchen_motion_sensor
  to: 'on'
condition:
  condition: or
  conditions:
    - condition: sun
      after: sunset
      after_offset: "-01:00:00"
    - condition: sun
      before: sunrise    
      before_offset: "-01:30:00"
    - condition: numeric_state
      entity_id: sensor.kitchen_lux
      below: 300
action:
- service: switch.turn_on
  entity_id: switch.kitchen_light
alias: motion kitchen light on
