trigger:
  platform: state
  entity_id: binary_sensor.tuyatec_kitchen_motion
  to: 'off'
  for: 00:05:00
action:
- service: switch.turn_off
  target:
    entity_id: 
    - switch.kitchen_light
    - switch.zwave_kitchen_sink_light
alias: motion kitchen light off
