trigger:
  platform: state
  entity_id: binary_sensor.tuyatec_zn9wyqtr_rh3040_5c3522fe_ias_zone
  to: 'on'
action:
  service: switch.turn_on
  entity_id: switch.laundry_light
alias: motion laundry light on
