triggers:
  trigger: state
  entity_id: binary_sensor.tuyatec_laundry_room_motion
  to: 'off'
  for: 00:05:00
actions:
- action: switch.turn_off
  entity_id: switch.laundry_light_switch
alias: motion laundry light off
id: laundrylightoff
