id: '1663687518380'
alias: Warm my feet
description: ''
trigger:
- type: occupied
  platform: device
  device_id: e1086f7688dc98bb375f52ded19b8956
  entity_id: binary_sensor.hue_office_motion_motion
  domain: binary_sensor
condition:
- condition: and
  conditions:
  - type: is_temperature
    condition: device
    device_id: e1086f7688dc98bb375f52ded19b8956
    entity_id: sensor.hue_office_temperature
    domain: sensor
    below: 70
  - condition: time
    before: 17:00:00
    after: 07:00:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
- service: switch.turn_on
  data: {}
  target:
    area_id: office
    device_id: 0c4e2de7b2064a1a02d616d0c1448b11
mode: single