id: '1663630675004'
alias: Preheat Espresso Machine
description: ''
triggers:
  - trigger: time
    at: 06:30:00
condition: 
  or:
  - condition: state
    entity_id: person.john_timon
    state: home
actions:
  - action: switch.turn_on
    data: {}
    target:
      entity_id: switch.kasa_dining_room_espresso_machine
mode: single
