id: "1670254277871"
alias: Power Off Espresso Machine
description: ""
triggers:
  - trigger: time
    at: "10:00:00"
condition: []
actions:
  - action: switch.turn_off
    data: {}
    target:
      entity_id: switch.kasa_dining_room_espresso_machine
mode: single
