id: '1663630675004'
alias: Preheat Espresso Machine
description: ''
trigger:
- platform: time
  at: 06:00:00
condition: 
  or:
  - condition: state
    entity_id: person.john_timon
    state: home
  - condition: state
    entity_id: person.oscar
    state: home
action:
- service: switch.turn_on
  data: {}
  target:
    entity_id: switch.espresso_machine
mode: single
