id: '1663630675004'
alias: Preheat Espresso Machine
description: ''
trigger:
- platform: time
  at: 06:00:00
condition:
- condition: state
  entity_id: person.john_timon
  state: home
action:
- service: switch.turn_on
  data: {}
  target:
    device_id: 12023f5a19c854bbdd567e4d81df484b
mode: single
