id: "officeheatingpad"
alias: Power Off Office Heating Pad
description: ""
trigger:
  - platform: time
    at: "17:00:00"
condition: []
action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.zwave_office_plug
mode: single
