id: "officeheatingpad"
alias: Power Off Office Heating Pad
description: ""
triggers:
  - trigger: time
    at: "17:00:00"
condition: []
actions:
  - action: switch.turn_off
    data: {}
    target:
      entity_id: switch.zwave_office_plug
mode: single
