binary_sensor:
  - name: John In Bed
    unique_id: john_in_bed
    state: >
      {{ (states('sensor.johns_side')|float) > 100 or (states('sensor.bed_weight')|float) > (states('sensor.home_occupancy_count') | float * 100 ) }}
  - name: Christine In Bed
    unique_id: christine_in_bed
    state: >
      {{ (states('sensor.christines_side')|float) > 100 or (states('sensor.bed_weight')|float) > (states('sensor.home_occupancy_count') | float * 100 ) }}


sensor:
  - name: Bed Weight
    unique_id:  total_bed_weight
    state_class: measurement
    unit_of_measurement: lb 
    state: >
      {% set total_weight = (states('sensor.johns_side') | float) + (states('sensor.christines_side') |float) %}
      {{ total_weight | float }}
    
  - name: Bed Occupancy Count
    unique_id:  how_many_people_in_bed
    state_class: measurement
    state: > 
      {% if states('sensor.bed_weight')|float > 200 %}
      2
      {% elif states('sensor.bed_weight')|float > 100 %}
      1
      {% else %}
      0
      {% endif %}


  - name: Home Occupancy Count
    unique_id: home_occupancy_count_id
    state_class: measurement
    state: > 
      {% if states('person.john_timon') == "home" and states('person.christine') == "home" %}
      2
      {% elif states('person.john_timon') == "home" or states('person.christine') == "home" %}
      1
      {% else %}
      0
      {% endif %}