esphome:
  name: fish-tank-flood

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "35343c0ad22175e0f6c3b583687c40e0"

wifi:
  networks:
  - ssid: !secret downstairs_ssid
    password: !secret wifi_password
    priority: 10
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

sensor:
  - platform: adc
    pin: A0
    name: "Fish Tank Flood"
    update_interval: 10s
    unit_of_measurement: "%"
#    filters:
#    - median:
#        window_size: 7
#        send_every: 4
#        send_first_at: 1
#    - calibrate_linear:
#        - 0.85 -> 0.00
#        - 0.44 -> 100.00
#    - lambda: if (x < 1) return 0; else return (x);
#    accuracy_decimals: 0
