esphome:
  name: kitchen-sink-water-flow

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "04aea39892c095a0fd6d814f586498f0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kitchen-Sink-Water-Flow"
    password: "Ta90SSpMSytz"

sensor:
  - platform: pulse_counter
    name: "Flow rate"
    pin: D1
    update_interval: 10s
    filters:
    - lambda: return (x / 23.0);
    unit_of_measurement: "L/m"  
    total:
      name: "Water Total"
      unit_of_measurement: "L"
      accuracy_decimals: 3
      filters:
        - multiply: 0.23
    