esphome:
  name: outdoor-shower-water-flow

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: "04aea39892c095a0fd6d814f586498f0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


sensor:
  - platform: pulse_counter
    name: "Flow rate"
    pin: D1
    update_interval: 1s
    filters:
    - lambda: return (x * 7.5 );
    unit_of_measurement: "L/m"  
    total:
      name: "Water Total"
      unit_of_measurement: "L"
      accuracy_decimals: 3
      filters:
        - multiply: 0.016

  - platform: ntc
    sensor: resistance_sensor
    name: Shower Temperature
    unit_of_measurement: °F
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm

  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: UPSTREAM
    resistor: 10kOhm
    name: Resistance Sensor
  
  - platform: adc
    pin: A0
    id: source_sensor
    update_interval: never
    filters:
      - multiply: 3.3
   

switch:
  - platform: gpio
    pin: D5
    id: ntc_vcc

interval:
  - interval: 10s
    then:
      - switch.turn_on: ntc_vcc
      - component.update: source_sensor
      - switch.turn_off: ntc_vcc
