esphome:
  name: masterbedroom-bed-controller

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "111f1155588fa84d2c83af7add9c3f69"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


light:
  - platform: fastled_clockless
    chipset: WS2812b
    pin: GPIO16
    num_leds: 115
    rgb_order: GRB
    name: "Left Underbed"
    effects:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 50%
              green: 0%
              blue: 0%
              num_leds: 10
            - red: 0%
              green: 0%
              blue: 50%
              num_leds: 10
          add_led_interval: 100ms
          reverse: False
      - addressable_twinkle:
          name: Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_scan:
          name: Scan Effect With Custom Values
          move_interval: 10ms
          scan_width: 5

  - platform: fastled_clockless
    chipset: WS2812b
    pin: GPIO17
    num_leds: 115
    rgb_order: GRB
    name: "Right Underbed"
    effects:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 50%
              green: 0%
              blue: 0%
              num_leds: 10
            - red: 0%
              green: 0%
              blue: 50%
              num_leds: 10
          add_led_interval: 100ms
          reverse: False
      - addressable_twinkle:
          name: Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_scan:
          name: Scan Effect With Custom Values
          move_interval: 10ms
          scan_width: 5
