esphome:
  name: masterbedroom-bed-controller

esp32:
  board: esp32dev
  framework:
    type: arduino

globals:
  - id: christine_initial_zero
    type: float
    restore_value: 'yes'
    initial_value: '-2021482'

  - id: john_initial_zero
    type: float
    restore_value: 'yes'
    initial_value: '-1471991'

  - id: auto_tare_enabled
    type: bool
    restore_value: 'yes'
    initial_value: 'true'

  - id: christine_auto_tare_difference
    type: float
    restore_value: 'yes'
    initial_value: '0'

  - id: john_auto_tare_difference
    type: float
    restore_value: 'yes'
    initial_value: '0'

# Enable logging
logger:
  level: INFO
#  logs:
#    hx711: INFO

# enable mqtt
mqtt:
  broker: 192.168.1.30
  
# Enable Home Assistant API
api:

ota:
  password: "111f1155588fa84d2c83af7add9c3f69"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

button:
  - platform: template
    id: bed_sensor_tare_action_switch
    name: Bed Manual Tare
    icon: mdi:scale-balance
    on_press: 
      - lambda: |-
          id(christine_auto_tare_difference) = id(christine_initial_zero) - id(christines_side_raw).state;
          id(john_auto_tare_difference) = id(john_initial_zero) - id(johns_side_raw).state;
         

light:
  #- platform: monochromatic
  #  name: "Headboard Lights"
  #  output: headboard_light
  - platform: fastled_clockless
    chipset: WS2812b
    pin: GPIO16
    num_leds: 115
    rgb_order: GRB
    name: "Left Underbed"
    effects:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 50%
              green: 0%
              blue: 0%
              num_leds: 10
            - red: 0%
              green: 0%
              blue: 50%
              num_leds: 10
          add_led_interval: 100ms
          reverse: False
      - addressable_twinkle:
          name: Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_scan:
          name: Scan Effect With Custom Values
          move_interval: 10ms
          scan_width: 5

  - platform: fastled_clockless
    chipset: WS2812b
    pin: GPIO17
    num_leds: 115
    rgb_order: GRB
    name: "Right Underbed"
    effects:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 50%
              green: 0%
              blue: 0%
              num_leds: 10
            - red: 0%
              green: 0%
              blue: 50%
              num_leds: 10
          add_led_interval: 100ms
          reverse: False
      - addressable_twinkle:
          name: Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_scan:
          name: Scan Effect With Custom Values
          move_interval: 10ms
          scan_width: 5

#output:
#  - platform: ledc
#    id: headboard_light
#    pin: GPIO13

sensor:
  - platform: hx711
    id: johns_side_raw
    name: johns side raw
    internal: False
    dout_pin: GPIO19
    clk_pin: GPIO18
    gain: 128
    update_interval: 1s
    filters:
      - quantile:
          window_size: 10
          send_every: 1
          send_first_at: 1
          quantile: .9
    on_value:
      then:
        - sensor.template.publish:
            id: johns_side
            state: !lambda 'return id(johns_side_raw).state;'
        - if:
            condition:
              and:
                - lambda: 'return id(auto_tare_enabled);'
                # no one is home
                - lambda: 'return id(johns_side_raw).state < 10.0;'
            then:
              - if:
                  condition:
                    - lambda: 'return id(johns_side_raw).state < (id(john_initial_zero) - id(john_auto_tare_difference));'
                  then:
                    - lambda: |-
                        id(john_auto_tare_difference) += 10;
                  else:
                    - lambda: |-
                        id(john_auto_tare_difference) -= 10;

  - platform: hx711
    id: christines_side_raw
    name: christines side raw
    internal: False
    dout_pin: GPIO32
    clk_pin: GPIO33
    gain: 128
    update_interval: 1s
    filters:
      - quantile:
          window_size: 10
          send_every: 1
          send_first_at: 1
          quantile: .9
    on_value:
      then:
        - sensor.template.publish:
            id: christines_side
            state: !lambda 'return id(christines_side_raw).state;'
        - if:
            condition:
              and:
                - lambda: 'return id(auto_tare_enabled);'
                # no one is home
                - lambda: 'return id(christines_side_raw).state < 10.0;'
            then:
              - if:
                  condition:
                    - lambda: 'return id(christines_side_raw).state < (id(christine_initial_zero) - id(christine_auto_tare_difference));'
                  then:
                    - lambda: |-
                        id(christine_auto_tare_difference) += 10;
                  else:
                    - lambda: |-
                        id(christine_auto_tare_difference) -= 10;

  - platform: template
    id: christines_side
    name: Christines Side
    internal: False
    filters:
      - lambda: 'return x + id(christine_auto_tare_difference);'
      - calibrate_linear:
          - -2021482 -> 0
          - -2599781 -> 180
      - lambda: |-
          if (x <= 0.1) { return 0.0;}
          else {return x;}
    unit_of_measurement: lb
    accuracy_decimals: 2
    update_interval: never

  - platform: template
    id: johns_side
    name: Johns Side
    internal: False
    filters:
      - lambda: 'return x + id(john_auto_tare_difference);'
      - calibrate_linear:
          - -1471991 -> 0
          - -2250806 -> 190
      - lambda: |-
          if (x <= 0.1) { return 0.0;}
          else {return x;}
    unit_of_measurement: lb
    accuracy_decimals: 2
    update_interval: never

#esp32_touch:
#  setup_mode: false
#
#binary_sensor:
#  - platform: esp32_touch
#    name: "Touch Pad 2"
#    pin: GPIO27
#    threshold: 800
#  - platform: esp32_touch
#    name: "Touch Pad 1"
#    pin: GPIO14
#    threshold: 800
