esphome:
  name: masterbedroom-bed-controller

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "111f1155588fa84d2c83af7add9c3f69"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


light:
  - platform: monochromatic
    name: "Headboard Lights"
    output: headboard_light
  - platform: fastled_clockless
    chipset: WS2812b
    pin: GPIO16
    num_leds: 115
    rgb_order: GRB
    name: "Left Underbed"
    effects:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 50%
              green: 0%
              blue: 0%
              num_leds: 10
            - red: 0%
              green: 0%
              blue: 50%
              num_leds: 10
          add_led_interval: 100ms
          reverse: False
      - addressable_twinkle:
          name: Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_scan:
          name: Scan Effect With Custom Values
          move_interval: 10ms
          scan_width: 5

  - platform: fastled_clockless
    chipset: WS2812b
    pin: GPIO17
    num_leds: 115
    rgb_order: GRB
    name: "Right Underbed"
    effects:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 50%
              green: 0%
              blue: 0%
              num_leds: 10
            - red: 0%
              green: 0%
              blue: 50%
              num_leds: 10
          add_led_interval: 100ms
          reverse: False
      - addressable_twinkle:
          name: Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_scan:
          name: Scan Effect With Custom Values
          move_interval: 10ms
          scan_width: 5

output:
  - platform: ledc
    id: headboard_light
    pin: GPIO13

sensor:
  - platform: hx711
    name: "John's Side"
    dout_pin: GPIO19
    clk_pin: GPIO18
    gain: 128
    update_interval: 1s # ishak 0.2
    filters:
      - calibrate_linear:
          - -1471991 -> 0
          - -2245691 -> 190
      - sliding_window_moving_average:
          window_size: 3
          send_every: 1
#          send_first_at: 10
    unit_of_measurement: lb
    accuracy_decimals: 2
  - platform: hx711
    name: "Christine's Side"
    dout_pin: GPIO32
    clk_pin: GPIO33
    gain: 128
    update_interval: 1s # ishak 0.2
    filters:
       - calibrate_linear:
          - -1891389 -> 0
          - -2385951 -> 180
       - sliding_window_moving_average:
          window_size: 3
          send_every: 1
#          send_first_at: 10
    unit_of_measurement: lb
    accuracy_decimals: 2

esp32_touch:
  setup_mode: false

binary_sensor:
  - platform: esp32_touch
    name: "Touch Pad 2"
    pin: GPIO27
    threshold: 800
  - platform: esp32_touch
    name: "Touch Pad 1"
    pin: GPIO14
    threshold: 800

