esphome:
  name: master-bathroom-led

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "fd81202483b0870d0c3fce13750fde9f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Example configuration entry
light:
  - platform: monochromatic
    name: "Master Bathroom LED lights"
    output: output_component1

# Example output entry
output:
  - platform: esp8266_pwm
    id: output_component1
    pin: D1